-- Insert default menu items
INSERT INTO menu_items (categorie, nume,cantitate_ml,pret_lei,descriere) VALUES 
('Long Drinks', 'Sex On The Beach', 300, 30, 'Suc Ananas, Suc Merisoare, Suc Portocale, Vodca, Lichior Piersici'),
('Long Drinks', 'Mojito', 300, 30, 'Rom, Apa Minerala, Zahar Brun, Lime, Menta'),
('Long Drinks', 'Cuba Libre', 300, 30, 'Rom, Lime, Pepsi'),
('Long Drinks', 'Bumbu Libre', 300, 30, 'Rom Bumbu, Lime, Pepsi'),
('Long Drinks', 'Tequila Sunrise', 300, 30, 'Tequila, Suc Portocale, Grenadine'),
('Long Drinks', 'Gin Tonic', 300, 30, 'Gin, Apa Tonica, Lime'),
('Long Drinks', 'Aperol Spritz', 300, 30, 'Aperol, Prosecco, Apa Minerala, Portocala'),
('Long Drinks', 'Hugo', 300, 30, 'Sirop Soc, Prosecco, Menta, Lime, Apa Minerala'),
('Long Drinks', 'Campari Orange', 300, 30, 'Campari, Suc Portocale, Portocala'),
('Long Drinks', 'Campari Soda', 300, 30, 'Campari, Apa Minerala, Portocala'),
('Long Drinks', 'Campari Tonic', 300, 30, 'Campari, Apa Tonica, Portocala'),
('Long Drinks', 'Vodka Juice', 300, 30, 'Vodca, Sucuri'),
('Long Drinks', 'Whiskey Juice', 300, 30, 'Whiskey, Sucuri'),
('Long Drinks', 'Long Island', 300, 40, 'Triplu Sec, Rom, Gin, Vodka, Tequila, Pepsi, Lamaie, Menta'),
('Long Drinks', 'Blue Lagoon', 300, 30, 'Sour Vodka, Suc Lamaie, Apa Minerala, Blue Curacao'),
('Long Drinks', 'Martini Royale', 250, 30, 'Martini, Prosecco, Lime, Menta'),
('Long Drinks', 'Limoncello Spritz', 350, 30, 'Limoncello, Prosecco, Lime, Apa minerala'),
('Beer', 'Tuborg Draught', 400, 14, NULL),
('Beer', 'Skol Draught', 400, 12, NULL),
('Beer', 'Bucur Draught', 400, 17, NULL),
('Beer', 'Tuborg Sticla', 330, 14, NULL),
('Beer', 'Bucur', 330, 17, NULL),
('Beer', 'Calsberg', 330, 17, NULL),
('Beer', 'Skol', 330, 12, NULL),
('Beer', 'Bucur Brun', 330, 20, NULL),
('Beer', 'Calsberg Doza', 500, 17, NULL),
('Beer', 'Tuborg Doza', 500, 14, NULL),
('Beer', 'Skol Doza', 500, 12, NULL),
('Beer', 'Somersby', 330, 15, NULL),
('Beer', 'Corona', 355, 20, NULL),
('Wine', 'Purcari Sauvignon Blanc', 750, 90, NULL),
('Wine', 'Purcari Chardonnay', 750, 90, NULL),
('Wine', 'Purcari Rose de Purcari', 750, 90, NULL),
('Wine', 'Purcari Nocture Chardonnay', 750, 130, NULL),
('Wine', 'Purcari Nocture Rose', 750, 130, NULL),
('Wine', 'Murfatlar Aerosoli Fet. Regala', 750, 90, NULL),
('Wine', 'Murfatlar Aerosoli Rose', 750, 90, NULL),
('Wine', 'Caii de la Letea Aligote', 750, 90, NULL),
('Wine', 'Caii de la Letea Rose', 750, 90, NULL),
('Wine', 'Recas Sole Chardonnay', 750, 150, NULL),
('Wine', 'Rasova La Plage Alb', 750, 90, NULL),
('Wine', 'Rasova La Plage Rose', 750, 90, NULL),
('Wine', 'Rasova Prosecco', 750, 90, NULL),
('Wine', 'Averesti Sauvignon Demisec', 750, 80, NULL),
('Wine', 'Averesti Rose Demisec', 750, 80, NULL),
('Wine', 'Frizante Bianco', 200, 15, NULL),
('Wine', 'Vin la pahar', 200, 15, NULL),
('Spirits', 'Jack Daniels', 50, 20, NULL),
('Spirits', 'J&B', 50, 15, NULL),
('Spirits', 'Johny Walker Red', 50, 15, NULL),
('Spirits', 'Johny Walker Black', 50, 25, NULL),
('Spirits', 'Vodka Absolut', 50, 15, NULL),
('Spirits', 'Vodka Finlandia', 50, 15, NULL),
('Spirits', 'Vodka Zubrowka Czarna', 50, 15, NULL),
('Spirits', 'Rom Havana', 50, 15, NULL),
('Spirits', 'Rom Bumbu', 50, 25, NULL),
('Spirits', 'Gin Beefeater', 50, 15, NULL),
('Spirits', 'Tequila', 30, 15, NULL),
('Spirits', 'Jagermeister', 50, 20, NULL),
('Spirits', 'Cognac Jidvei', 50, 15, NULL),
('Spirits', 'Metaxa', 50, 15, NULL),
('Spirits', 'Martini Bianco', 50, 15, NULL),
('Spirits', 'Campari', 50, 15, NULL),
('Bacardi Breezer','Bacardi Breezer', 285, 25, NULL),
('Virgin Cocktails', 'Green Apple', 300, 25, 'Lime, Suc Mere, Grenadine, Portocala'),
('Virgin Cocktails', 'Citrus Sunrise', 300, 25, 'Suc Portocale, Grenadine, Portocala'),
('Virgin Cocktails', 'Milk Shake', 300, 25, 'Lapte, Topping, Inghetata, Frisca'),
('Virgin Cocktails', 'Limonada', 300, 20, 'Lamaie, Apa Plata, Menta, Zahar'),
('Virgin Cocktails', 'Limonada Fructata', 300, 25, 'Lamaie, Apa Plata, Zahar, Topping capsuni / mango'),
('Virgin Cocktails', 'Virgin Mojito', 300, 25, 'Lime, Menta, Apa Tonica, Zahar Brun'),
('Virgin Cocktails', 'Gin Tonic N.A.', 300, 30, 'Gin N.A., Apa Tonica, Lime'),
('Coffee', 'Espresso', 30, 10, NULL),
('Coffee', 'Espresso Doppio', 60, 20, NULL),
('Coffee', 'Cappuccino', 200, 12, NULL),
('Coffee', 'Latte', 200, 25, NULL),
('Coffee', 'Flat White', 200, 20, 'Espresso dublu, spuma de lapte'),
('Coffee', 'Espresso Deco', 30, 10, NULL),
('Coffee', 'Cafe Frappe', 400, 23, 'Nescaffe, lapte, topping ciocolata, topping caramel, zahar, spray vegetal'),
('Coffee', 'Cafe Frappe cu Inghetata', 400, 25, 'Nescaffe, lapte, topping ciocolata, topping caramel, inghetata, zahar, spray vegetal'),
('Soft Drinks', 'Cola', 500, 14, NULL),
('Soft Drinks', 'Fanta', 500, 14, NULL),
('Soft Drinks', 'Sprite', 500, 14, NULL),
('Soft Drinks', 'Schweppes', 500, 14, NULL),
('Soft Drinks', 'Fuzetea', 500, 14, NULL),
('Soft Drinks', 'Cola', 250, 12, NULL),
('Soft Drinks', 'Fanta', 250, 12, NULL),
('Soft Drinks', 'Sprite', 250, 12, NULL),
('Soft Drinks', 'Schweppes', 250, 12, NULL),
('Soft Drinks', 'RedBull', 250, 20, NULL),
('Soft Drinks', 'Cappy', 250, 13, NULL),
('Soft Drinks', 'Limonada Timbark', 400, 12, NULL),
('Soft Drinks', 'Timbark Fizzy', 400, 10, NULL),
('Soft Drinks', 'Doza de fresh', 250, 20, 'sucuri naturale'),
('Soft Drinks', 'Granini', 330, 10, NULL),
('Soft Drinks', 'Apa plata Bucovina', 500, 10, NULL),
('Soft Drinks', 'Apa plata Bucovina', 750, 15, NULL),
('Soft Drinks', 'Apa minerala Bucovina', 500, 10, NULL),
('Soft Drinks', 'Apa minerala Bucovina', 750, 15, NULL),
('Soft Drinks', 'Apa Tymbark Fructata', 500, 12, NULL),
ON CONFLICT (nume) DO NOTHING;
